# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Fire Fickell
email: bob@firefickell.com
description: >- # this means to ignore newlines until "baseurl:"
  I'm still giving Luke Fickell a chance, but know people who send this link
  around a lot. I was surprised that no one had bought the domain. So I bought
  it. Not sure what to put here yet.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://firefickell.com" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: jekyllrb
# github_username: jekyll

# Build settings
theme: minimal-mistakes-jekyll
plugins:
  - jekyll-feed
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Customizations

minimal_mistakes_skin: "air"
repository: firefickell/firefickell.com
hero_image: "./img/flask.jpeg"
header_image: ".img/flask.jpeg"

# Recommended defaults by author of this them
# per https://mmistakes.github.io/minimal-mistakes/docs/posts/

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true

include:
  - img
# comments:
#   provider: "giscus"
#   giscus:
#     repo_id              : R_kgDOM7_Sdg # Shown during giscus setup at https://giscus.app
#     category_name        : General # Full text name of the category
#     category_id          : DIC_kwDOM7_Sds4CjHZH # Shown during giscus setup at https://giscus.app
#     discussion_term      : pathname # "pathname" (default), "url", "title", "og:title"
#     reactions_enabled    : 1 # '1' for enabled (default), '0' for disabled
#     theme                : light
